[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port 4173"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
VITE_API_URL = "https://web-production-e67c7.up.railway.app"
