[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./calendar-backend"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DATABASE_URL = "calendar.db"
