[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./calendar-backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
GIN_MODE = "release"
