[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
VITE_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
